config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :servings, presence: true, numericality: { only_integer: true }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Private functions
  private

  # Converts email to all lower-case
  def downcase_email
    self.email.downcase!
  end

  # Creates and assigns the activation token and digest
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_token = User.digest(activation_token)
  end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.update_attribute(:activated, true)
      user.update_attribute(:activated_at, Time.zone.now)
      log_in user
      flash[:succes] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message = "Account not activated. "
        message += "Check your email for the activation link"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to root_url
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Your account has been deleted"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :servings, :password, :password_confirmation)
  end

  #Before filters

  # Confirms a logged-in user
  def logged_in_user
    unless logged_in?
      store_location
      flash[:error] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true fi the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default)
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <%= render 'partials/header' %>
  <div id="main">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "flash-#{message_type}") %>
      <% end %>
    
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "Vegan for a Week") %>


<section class="first-row">

<article class="info">
<h1>Vegan for a Week</h1>
<h2>I built this web app to make it easier for people like me, who have followed an animal-based diet for most of their lives, to try out the vegan life. You can view the recipes I've written, or you can create an account to get a meal plan tailored for you.</h2>

I recently tried to follow a vegan diet for one week. My girlfriend had recently started eating vegan only, so I figured I would be supportive and join her. I liked it so much that I'm still doing it.
</article> 
</section>

app/views/partials/_form.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
    
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :servings, "For how many people are you cooking?" %>
      <%= f.text_field :servings %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Re-enter your password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit yield(:button_text) %>

<% end %>

app/views/partials/_header.html.erb
<%= render 'refills/centered_navigation' %>

app/views/refills/_centered_navigation.html.erb
<header class="centered-navigation" role="banner">
  <div class="centered-navigation-wrapper">
     <%= link_to(image_tag("logo.svg", alt: "logo"), root_url, class: "mobile-logo") %>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">Menu</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
        <li class="nav-link"><a href="javascript:void(0)">Recipes</a></li>
        <li class="nav-link"><a href="javascript:void(0)">About Veganism</a></li>
        <li class="nav-link logo">
           <%= link_to(image_tag("logo.svg", alt: "logo"), root_url, class: "logo") %>
        </li>
        <% if logged_in? %>
        <li id="js-centered-more" class="nav-link more">Account
        <ul class="submenu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          </ul>
          </li>
        <li class="nav-link"><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
        <li class="nav-link"><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="flash-error">
<h4>The form contains <%= pluralize(@user.errors.count, "error") %>.</h4>
 <ul>
	<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
</ul>
</div>




<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>
<% provide(:button_text, 'Save changes') %>
<section class="first-row">

<article class="info">
<h1>Update your profile</h1>

  <%= render 'partials/form' %>
  
</article>
<article class="info">
<h1>Delete your account</h1>
We'd hate to see you go, but if you really want to delete your account, press the button below.

</br></br>
  <%= button_to "Delete your account", @user, method: :delete, data: { confirm: "Are you sure?" } %>
</article>
</section>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<section class="first-row">

<article class="info">
    
    <h1>Sign up</h1>

    <%= render 'partials/form' %>

</article>

</section>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<section class="first-row">

<article class="info">
<h1>Hi, <%= @user.name %>!</h1>
<h2>Are you ready to start your vegan week?</h2>

You can view the recipes I've selected for you below. If you don't like a recipe, just click it to replace it with another one until you are satisfied! </br></br>

On the right, you can see the grocery list for the full week.
</article> 

<div class="grocery-list">
 <ul>
 <h3>Grocery list</h3>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 	<%= content_tag(:li, fa_icon("square-o li", text: "Example item")) %>
 </ul>
 </div>
</section>